modLoader = "javafml"
loaderVersion = "[1,)"

license = "MIT"
[[mods]]
modId = "ferritecore"
version = "${file.jarVersion}"
displayName = "Ferrite Core"
authors = "malte0811"
description = '''
Reduces memory usage.
'''
logoFile = "logo.png"
[[dependencies.ferritecore]]
modId = "neoforge"
mandatory = true
versionRange = "[20.4.11-beta,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ferritecore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="ferritecore.predicates.mixin.json"
[[mixins]]
config="ferritecore.fastmap.mixin.json"
[[mixins]]
config="ferritecore.mrl.mixin.json"
[[mixins]]
config="ferritecore.dedupmultipart.mixin.json"
[[mixins]]
config="ferritecore.blockstatecache.mixin.json"
[[mixins]]
config="ferritecore.dedupbakedquad.mixin.json"
[[mixins]]
config="ferritecore.threaddetec.mixin.json"
[[mixins]]
config="ferritecore.modelsides.mixin.json"
